name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Download Dist
        env:
          Filename: ${{ github.sha }}.tar.gz
        run: |
          aws s3 cp s3://zhuhaolin.com/frontend/$Filename $Filename
          tar -xzvf $Filename
          mv dist app
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "app"
          target: "/var/www"
