name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
      - name: Upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude "*.html"
        env:
          AWS_S3_BUCKET: 'zhuhaolin.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: 'dist'
      - name: Build & Push image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: zhuhaolin/frontend-app:${{ github.sha }}
          username: bill_lord
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: registry.eu-west-1.aliyuncs.com
