name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
      - uses: actions/cache@v2
        with:
          path: |
            dist
            Dockerfile
          key: ${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            dist
            Dockerfile
          key: ${{ github.sha }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: registry.eu-west-1.aliyuncs.com
          username: bill_lord
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.eu-west-1.aliyuncs.com/zhuhaolin/frontend-app:${{ github.event.inputs.tag }}
