name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install & Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
      - name: Upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude "*.html"
        env:
          AWS_S3_BUCKET: 'zhuhaolin.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: 'dist'
      - name: Login Aliyun
        run: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} ${{ secrets.ALIYUN_REGISTRY_URL }}
      - name: Build & Push image to Aliyun
        env:
          REGISTRY: ${{ secrets.ALIYUN_REGISTRY_URL }}
          NAMESPACE: ${{ secrets.ALIYUN_REGISTRY_NAMESPACE }}
          REPOSITORY: frontend-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$NAMESPACE/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$NAMESPACE/$REPOSITORY:$IMAGE_TAG
