name: Merge Check

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 'latest'
      - run: pnpm install
      - run: pnpm build
